# .pre-commit-config.yaml

# See https://pre-commit.com for more information
# Hooks help you automatically format and lint your code before committing

repos:
  # Pre-commit Hooks Repository
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  # Prettier for Formatting Markdown and HTML
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
        name: Prettier file formatter
        files: \.(md|html|yaml)$
        types: [file]
        args: ["--write"]
